### ISSUE TITLE
cleanings parameter not working

### ISSUE THREAD

**Issue by StefanoGiu** [And3rsL/Deebot-for-hassio#10]
Passing the value 2 doesn't  have effect... It always do one cleaning.

**Comment by And3rsL** [comment]
did you try it by the app? it cleans twice the same spot

**Comment by StefanoGiu** [comment]
The app cleans twice the same room, yes

**Comment by StefanoGiu** [comment]
I fixed it in this way ;)

            return self.device.SpotArea(params['rooms'], int(params['cleanings']))

**Comment by And3rsL** [comment]
thanks i will add it in the next release !
