### ISSUE TITLE
Use standalone python script

### ISSUE THREAD

**Issue by StefanoGiu** [And3rsL/Deebot-for-hassio#11]
Hello, I don't know how to comment this one (so I opened an issue, sorry about that).

Is it possible to use the python standalone script without HA to trigger the vacuum? I was thinking to integrate the vacuum with google assistant via IFTTT :)

Hey Google, clean the kitchen :)

**Comment by And3rsL** [comment]
You can integrate google assistant thought scripts

Example:

'1585598092164':
  alias: Pulisci soggiorno
  sequence:
  - data:
      command: spot_area
      entity_id: vacuum.ambrogio
      params:
        cleanings: 1
        rooms: 5
    entity_id: vacuum.ambrogio
    service: vacuum.send_command

and then expose script to google assistant

**Comment by StefanoGiu** [comment]
I used Google Assistant --> IFTTT --> Webhooks-->HA--> automations--> script--> vacuum.py
