### ISSUE TITLE
[Question] Multiple Vacuum support?

### ISSUE THREAD

**Issue by laimoncijus** [And3rsL/Deebot-for-Hassio#110]
Hi there,

I was wondering if this component works well with multiple vacuums under the same account (same account email address)?

During the configuration phase I am able to see both of my vacuums, though after adding them do devices list - one of them is working fine and the 2nd is shown as "unavailable"...

Through the Ecovacs App I am able to control both of them with no issues, so it really surprises me why just one of them is shown properly in HA? 

Furthermore, some of the created entities, like "camera.<name>_livemap" for example, has proper data for all devices, just the "vacuum.<name>" for one is "docked" and for the other "unavailable".

Any ideas what could be wrong with the component or my local installation maybe?

Thanks in advance!

**Comment by And3rsL** [comment]
It should, what is the model of the one that isn't working ?

**Comment by laimoncijus** [comment]
Deebot Ozmo 950 and it was working before without problems (configured via YAML).

Today I also added Deebot ozmo 920 and moved from YAML to GUI configuration - and now 950 isn't working and 920 is shown ok...

**Comment by laimoncijus** [comment]
Seems I didn't switch from YAML to GUI configuration properly... 

I did now remove all entities, followed by a restart HA to clean everything up and configured the integration again - everything is working fine.
