### ISSUE TITLE
Trying to use xiaomi lovelace card

### ISSUE THREAD

**Issue by fenderle** [And3rsL/Deebot-for-hassio#13]
This card is able to be configured so I can use it for my Ozmo 950 - with one exception: It does not show the state since it uses the attribute status for that. Would it be possible that you copy the state over to a new attribute 'status' or 'state'?

I know that's duplication but all other vacs seem to use an attribute to report their status.

**Comment by And3rsL** [comment]
Added:
https://github.com/And3rsL/Deebot-for-hassio/commit/b0720f3f2f18ab5edd6e23f2fce23cb1044e8854
