### ISSUE TITLE
Faster status feedback

### ISSUE THREAD

**Issue by ardupic** [And3rsL/Deebot-for-hassio#14]
Hi,
is there a way to receive on HA a faster status feedback?
i mean, when it start or goes back to the dock, status feedback is delayed of 10 or 20 seconds, it would be great if cleaning, paused and docked will change immediatly
thanks

**Comment by And3rsL** [comment]
Hi, you can specify update interval

Follow this guide:
https://www.home-assistant.io/docs/configuration/platform_options/
