### ISSUE TITLE
Update 1.8.1 Boot Loop

### ISSUE THREAD

**Issue by Veuchez** [And3rsL/Deebot-for-hassio#22]
Hi!
Update 1.8.0 e 1.8.1 creates a Home Assistant boot loop for me.
Only by uninstalling the integration does the Boot Loop stop and I can reuse Home Assistant.
Is there any solution?
I have Home Assistant 0.110.3, Supervisor 224, HassOS 3.13 and HACS 1.0.3
Thanks!

**Comment by And3rsL** [comment]
What hardware do you use?

**Comment by irdetokey** [comment]
Same for me, running on qnap hassos 3.13 virtualized.
thanks
Alex

**Comment by Veuchez** [comment]
It's a VM on Vsphere 7.

**Comment by And3rsL** [comment]
Can you access FTP and get home assistant log while Is in bootloop?

**Comment by Veuchez** [comment]
I don't think it's a performance issue with 4 vCPUs and 6GB of dedicated RAM.
Now I see if I can get the log.

**Comment by And3rsL** [comment]
> I don't think it's a performance issue with 4 vCPUs and 6GB of dedicated RAM.
> Now I see if I can get the log.
You are right :D

maybe a home assistant cap to performance, i dont know yet

**Comment by Veuchez** [comment]
I don't see any errors, how should I configure the logger?

**Comment by And3rsL** [comment]
It doesnt produce error

Put in configuration.yaml:
`
logger:
    default: debug
`

the critical point Is when It produce the PNG map you should look forward to 'GetBase64Map' and trace It

**Comment by Veuchez** [comment]
2020-05-27 19:42:14 DEBUG (schedule_thread_livemap) [deebotozmo] Trace Request: TotalCount=610 traceStart=0
2020-05-27 19:42:14 DEBUG (schedule_thread_livemap) [deebotozmo.map] decompress7zBase64Data begin
2020-05-27 19:42:14 DEBUG (schedule_thread_livemap) [deebotozmo.map] decompress7zBase64Data done
2020-05-27 19:42:15 DEBUG (schedule_thread_livemap) [deebotozmo] Trace Request: TotalCount=610 traceStart=200
2020-05-27 19:42:15 DEBUG (schedule_thread_livemap) [deebotozmo.map] decompress7zBase64Data begin
2020-05-27 19:42:15 DEBUG (schedule_thread_livemap) [deebotozmo.map] decompress7zBase64Data done

These are the only rumors, I don't see any mistakes though ..

**Comment by hanlongwang** [comment]
I'm seeing the issue, getting 100% CPU usage and getting constant bootloops from this.

I now isolated a second docker HA instance with just this integration and still seeing it.

**Comment by Veuchez** [comment]
Problem solved with version 1.9.1.
Thanks for the great work!

**Comment by And3rsL** [comment]
> Problem solved with version 1.9.1.
> Thanks for the great work!

Happy to hear that 😄
