### ISSUE TITLE
Support for T8?

### ISSUE THREAD

**Issue by webhostsg** [And3rsL/Deebot-for-hassio#33]
Thinking of buying T8, will it work with this?

**Comment by skynetua** [comment]
Yes, checked on my ozmo t8 aivi

**Comment by webhostsg** [comment]
> Yes, checked on my ozmo t8 aivi

Thank you so much

**Comment by skynetua** [comment]
You are welcome. Great vacuum btw, can recommend :)

**Comment by And3rsL** [comment]
nice to hear that! added to supported models

**Comment by gmkrib** [comment]
It is also working with the ozmo T8 and T8+
