### ISSUE TITLE
SUPPORTED ROBOT

### ISSUE THREAD

**Issue by And3rsL** [And3rsL/Deebot-for-hassio#35]
At this moment only these robot seems to be supported:

DEEBOT OZMO 950
DEEBOT OZMO 960
DEEBOT OZMO 920
DEEBOT OZMO T8 AIVI

Please comment below if you tried another model and its working fine :)

## I will not support other models or features that its not included in the 950 model. since i have this one and i cant debug others :)

**Comment by Mills79** [comment]
I have the OZMO 920 I've gor the live map feature working but I'm struggaling with the 'clean area' feature.  Where do you enter the clean area code. I've tried it in the code section of a custom card but it doesnt work

**Comment by edenhaus** [comment]
There are 3 communication variants used by Ecovacs for the Deebot vacuum cleaners:
- XMPP (e.g. Slim 2, N79, OZMO 930)
- MQTT/XML (e.g. Deebot 900, OZMO 900)
- **MQTT/JSON (e.g. OZMO 920/950, T8 series) We only support this variant until now**
