### ISSUE TITLE
user/login failed with code: '0002 '

### ISSUE THREAD

**Issue by DaaXDooR** [And3rsL/Deebot-for-hassio#37]
Protokolldetails ( ERROR )
Logger: deebotozmo
Source: custom_components/deebot/vacuum.py:94 
First occurred: 19:26:25 (1 occurrences) 
Last logged: 19:26:25

call to user/login failed with {'code': '0002', 'msg': '校验异常', 'time': 7923874923749}

**Comment by And3rsL** [comment]
Can you confirm what country code and content code did you set up?

I had IT and WW , from this morning i recive this errors too, setting IT and EU solve the problem

**Comment by DaaXDooR** [comment]
> Can you confirm what country code and content code did you set up?
> 
> 
> 
> I had IT and WW , from this morning i recive this errors too, setting IT and EU solve the problem
> 
> 
> 
> EDIT: Nevermind, it has user token cached .. 

thanks a lot that solved my problem :-)

**Comment by scribblrsam** [comment]
I have the same erros with settings uk and eu. Do you have any reccomendations?

**Comment by And3rsL** [comment]
Try multiple times to reebot home assistant. they changed something server side

**Comment by scribblrsam** [comment]
Thanks, an update seemed to clear the state.
