### ISSUE TITLE
Live map really small

### ISSUE THREAD

**Issue by aidbish** [And3rsL/Deebot-for-hassio#39]
**Describe the bug**
The map is tiny and i mean really small
**Configuration.yaml (Remember to delete your credentials)**
``

**System Informations:**
 - Device: [Deebot ozmo 920
 - Home Assistant Version: 0.114.3 ...
 - Hardware: micro pc.
 - Home Assistant Installation: ubunti server 20.04. HA container

Everything else is working fine, just the live map is small

**Comment by totalitarian** [comment]
Mine did that once. It sorted itself out after the next run out

**Comment by aidbish** [comment]
> Mine did that once. It sorted itself out after the next run out

Yeah tried that, still the same

**Comment by alberisca75** [comment]
it's happening to me too! tiny map below left with gray background!
have you solved?

**Comment by aidbish** [comment]
> it's happening to me too! tiny map below left with gray background!
> have you solved?

Hi i did, i changed the name of the map in the config, dont forget to change the map name in the camera config part also

livemappath: 'www/vac_map.png'
