### ISSUE TITLE
Request: More Information

### ISSUE THREAD

**Issue by KairuByte** [And3rsL/Deebot-for-hassio#42]
I was wondering if it would be possible to pull more information from the robots during cleaning?

Specifically I am wondering about total square footage/meterage and total elapsed time.

Error status/codes/messages would also be amazing.

**Comment by And3rsL** [comment]
New release add sensors domain, a big chance to increase number of informations!

**Comment by And3rsL** [comment]
Added stats to https://github.com/And3rsL/Deebot-for-hassio/releases/tag/1.9.6 release
