### ISSUE TITLE
Room ID not resetting

### ISSUE THREAD

**Issue by Bubbleshum** [And3rsL/Deebot-for-hassio#43]
After the map was lost on ecovacs deebot ozmo 920, I created a new map and now the room ids do not match. I tried to remove this component, removed the entity and reinstalled this component.

When the entity was found again, it seems to be taking the information from the database instead of writing new information.

Could you add in a refresh rooms function to allow new room ids to be created.

vacuum:
  - platform: deebot
    country: UK
    continent: EU
    deviceid: YOUR_ROBOT_ID

**System Informations:**
 - Device: Deebot ozmo 920
 - Home Assistant Version: 0.116.4
 - Hardware: Raspberry pi 4
 - Home Assistant Installation: Linux Hassos 4.14

**Additional context**
This function was working fine before my robot lost its map

**Comment by And3rsL** [comment]
new release should update rooms number correctly under sensor domain
