### ISSUE TITLE
Release new version with fixes of And3rsL/Deebotozmo#9

### ISSUE THREAD

**Issue by edenhaus** [And3rsL/Deebot-for-hassio#44]
Hi Andrea,

are you planning to release a new version with my fixes (And3rsL/Deebotozmo#9)?
On the 28. October a new HA version is released and I don't want install my fixes manually.

Thanks and saluti dall'alto adige

**Comment by And3rsL** [comment]
released 👍

**Comment by Vorms** [comment]
I still have problem !
When I check config, the error message is:
Invalid config for [vacuum.deebot]: [username] is an invalid option for [vacuum.deebot]. Check: vacuum.deebot->username. (See ?, line ?).

**Comment by edenhaus** [comment]
> I still have problem !
> When I check config, the error message is:
> Invalid config for [vacuum.deebot]: [username] is an invalid option for [vacuum.deebot]. Check: vacuum.deebot->username. (See ?, line ?).

Your problem has nothing to do with this issue, but I think you haven't read the release notes with the breaking change. (See https://github.com/And3rsL/Deebot-for-hassio/releases/tag/1.9.5)

**Comment by Vorms** [comment]
You are right !
Just read the doc !

Best regards
Thierry

Le dim. 1 nov. 2020 à 14:11, Robert Resch <notifications@github.com> a
écrit :

> I still have problem !
> When I check config, the error message is:
> Invalid config for [vacuum.deebot]: [username] is an invalid option for
> [vacuum.deebot]. Check: vacuum.deebot->username. (See ?, line ?).
>
> Your problem has nothing to do with this issue, but I think you haven't
> read the release notes with the breaking change. (See
> https://github.com/And3rsL/Deebot-for-hassio/releases/tag/1.9.5
> <https://mailtrack.io/trace/link/a36633c10a03fe3f37351a990fdf77ea36043768?url=https%3A%2F%2Fgithub.com%2FAnd3rsL%2FDeebot-for-hassio%2Freleases%2Ftag%2F1.9.5&userId=3563000&signature=3f261b34fe65faba>
> )
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/7f0dedb7744c6c1316c15b799da10541acdcb9ad?url=https%3A%2F%2Fgithub.com%2FAnd3rsL%2FDeebot-for-hassio%2Fissues%2F44%23issuecomment-720136868&userId=3563000&signature=f84a2a1fdb04f89f>,
> or unsubscribe
> <https://mailtrack.io/trace/link/a32ade64f502f0d3ba4000bb9716bd18d1101ad2?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA6QD4P2UHJLAXTYT5OKV3LSNWXFHANCNFSM4S5ZUZZQ&userId=3563000&signature=ee66e1594caceb90>
> .
>


-- 
Thierry Vorms
Québec Canada
