### ISSUE TITLE
Request: Allow for multiple devices

### ISSUE THREAD

**Issue by ehsman** [And3rsL/Deebot-for-hassio#46]
Thanks so much for all your work - your integration is awesome and allows people like me to add in their deebot in to Home Assistant.

Request: I have two deebots and would love to include them both in Home Assistant. With previous versions since we were under vacuum I could add multiple deebots. With your update to use deebot: I can no longer do this.

Though I could be completely wrong - and there may be a way to add multiple deebot's with your updated integration, and I just couldn't work out the yaml magic.

**Comment by And3rsL** [comment]
im currently working on that 👍

**Comment by And3rsL** [comment]
Should work on next release: https://github.com/And3rsL/Deebot-for-hassio/releases/tag/1.9.6

I currently doesnt have 2 robots, so please check and let me know

Thanks

**Comment by ehsman** [comment]
Thanks for the quick reply - and great work. I just did a super quick check and both vacuums indeed were added as entities:

<img width="1259" alt="Screen Shot 2020-11-02 at 11 02 44" src="https://user-images.githubusercontent.com/1527641/97908169-31a1fa00-1cfb-11eb-90cd-5c7aea9454e0.png">

But I did notice there was an issue in creating the rooms I believe. I have two T8+ (not AV) with not all the areas label. Some are still the default location and others I have chosen a label

The integration did create all the other sensors. Just not the room - so this might be a separate issue that I can raise as a separate issue if that makes it clearer and easier to track

2020-11-02 10:54:46 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 314, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 505, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/deebot/sensor.py", line 235, in state
    return int(self._vacbot.stats_time/60)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

**Comment by edenhaus** [comment]
> Thanks for the quick reply - and great work. I just did a super quick check and both vacuums indeed were added as entities:
> 
> <img alt="Screen Shot 2020-11-02 at 11 02 44" width="1259" src="https://user-images.githubusercontent.com/1527641/97908169-31a1fa00-1cfb-11eb-90cd-5c7aea9454e0.png">
> 
> But I did notice there was an issue in creating the rooms I believe. I have two T8+ (not AV) with not all the areas label. Some are still the default location and others I have chosen a label
> 
> The integration did create all the other sensors. Just not the room - so this might be a separate issue that I can raise as a separate issue if that makes it clearer and easier to track
> 
> 2020-11-02 10:54:46 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 314, in async_add_entities
> await asyncio.gather(*tasks)
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 505, in _async_add_entity
> await entity.add_to_platform_finish()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
> self.async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
> self._async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
> sstate = self.state
> File "/config/custom_components/deebot/sensor.py", line 235, in state
> return int(self._vacbot.stats_time/60)
> TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

The error form your log is going to be fixed in #52 
For the room the following issue was created #49 

@And3rsL or @ehsman can you please close this issue as it is resolved.
