### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'connect_and_wait_until_ready'

### ISSUE THREAD

**Issue by vadimag1** [And3rsL/Deebot-for-hassio#48]
Hi! I don't know much about programming. Please help. In "Home Assistant" can't install DEEBOT 950. Such error:
**Logger: homeassistant.setup
Source: custom_components/deebot/__init__.py:99
First occurred: 9:08:59 (1 occurrences)
Last logged: 9:08:59

Error during setup of component deebot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deebot/__init__.py", line 55, in setup
    HUB = DeebotHub(config[DOMAIN])
  File "/config/custom_components/deebot/__init__.py", line 99, in __init__
    self.vacbot.connect_and_wait_until_ready()
AttributeError: 'NoneType' object has no attribute 'connect_and_wait_until_ready'**

**Configuration.yaml**
# робот пылесос
deebot:
  username: v......11@live.ru
  password: 1..........0
  country: ru
  continent: eu
  deviceid: E...............6
    # Optional
  live_map: True                    # Enable Live Map.. may cause issues on low power hardware | Default: True
  show_color_rooms: False           # Enable draw room colors as in the app | Default: False
  livemappath: 'www/live_map.png'   # Path where to save live_map

**System Informations:**
 - Device: Deebot ozmo 950
 - Home Assistant Version: 0.117.1
 - Hardware: Raspberry
 - Home Assistant Installation: Windows

![99](https://user-images.githubusercontent.com/73733642/97795146-77d85a00-1c24-11eb-8030-27c94989af98.JPG)
![99_](https://user-images.githubusercontent.com/73733642/97795164-a6eecb80-1c24-11eb-96f1-3a7c05170279.JPG)

**Comment by And3rsL** [comment]
it seems that no robot was found, is "deviceID" correct? can you check?

**Comment by vadimag1** [comment]
Good afternoon! I'm sorry, Yes, DeviceID was recorded incorrectly. Everything worked out. Your product is great. Thanks.
