### ISSUE TITLE
Can't find rooms sensors on 1.9.5

### ISSUE THREAD

**Issue by ilnonno70** [And3rsL/Deebot-for-hassio#49]
**Describe the bug**
I've updated to 1.9.5 version.
I can't see rooms sensors as described in readme file.
I can't see rooms in UI too. In 1.9.4 version i was able to see them.

THx

**Configuration.yaml (Remember to delete your credentials)**
```

deebot:
    username: MY USER
    password: MY PSW
    country: it
    continent: eu
    deviceid: DEVICE ID
    live_map: True                    
    show_color_rooms: False           
    livemappath: 'www/live_map.png'

**System Informations:**
 - Device: [Deebot ozmo 950]
 - Home Assistant Version: 0.117.2
 - Hardware: Raspberry 4 8gb
 - Home Assistant Installation: Hassio

**Comment by And3rsL** [comment]
Hi,
Does home assistant log show any error/warning?
Do you see other sensors?

**Comment by ilnonno70** [comment]
HI And3rsL
HA doesn't show any error/warning in the log (but i'm not very skilled)
I can see only this about deebot
![sensor](https://user-images.githubusercontent.com/73182921/97848216-0b775c80-1cf1-11eb-9f17-2ec1bad59a45.JPG)
![vacuum](https://user-images.githubusercontent.com/73182921/97848224-0d412000-1cf1-11eb-841f-45d919e6919a.JPG)

**Comment by ilnonno70** [comment]
Today, after the last update I've got this two errors in the log.
I don't know if they can help you
![ERROR01](https://user-images.githubusercontent.com/73182921/97877430-79397d80-1d1d-11eb-96a2-f7b6317fe09c.JPG)
![ERROR02](https://user-images.githubusercontent.com/73182921/97877450-80f92200-1d1d-11eb-8f7e-71797291a3d6.JPG)

**Comment by ilnonno70** [comment]
I add this error from the log.

Logger: deebotozmo.ecovacsiotmq
Source: /usr/local/lib/python3.8/site-packages/deebotozmo/ecovacsiotmq.py:180
First occurred: 14:02:27 (9 occurrences)
Last logged: 20:06:08

1604340546.415141| Error calling API https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=yna5xi&did=4cb2afb0-d96f-49a5-8957-69bbb020597d&td=q&u=dk0gbvuc2643b256&cv=1.67.3&t=a&av=1.3.1 StatusCode 502
1604343084.403554| Error calling API https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=yna5xi&did=4cb2afb0-d96f-49a5-8957-69bbb020597d&td=q&u=dk0gbvuc2643b256&cv=1.67.3&t=a&av=1.3.1 StatusCode 502
1604343421.699576| Error calling API https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=yna5xi&did=4cb2afb0-d96f-49a5-8957-69bbb020597d&td=q&u=dk0gbvuc2643b256&cv=1.67.3&t=a&av=1.3.1 StatusCode 502
1604343465.409582| Error calling API https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=yna5xi&did=4cb2afb0-d96f-49a5-8957-69bbb020597d&td=q&u=dk0gbvuc2643b256&cv=1.67.3&t=a&av=1.3.1 StatusCode 502
1604343967.685214| Error calling API https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=yna5xi&did=4cb2afb0-d96f-49a5-8957-69bbb020597d&td=q&u=dk0gbvuc2643b256&cv=1.67.3&t=a&av=1.3.1 StatusCode 502

**Comment by edenhaus** [comment]
> Today, after the last update I've got this two errors in the log.
> I don't know if they can help you
> ![ERROR01](https://user-images.githubusercontent.com/73182921/97877430-79397d80-1d1d-11eb-96a2-f7b6317fe09c.JPG)
> ![ERROR02](https://user-images.githubusercontent.com/73182921/97877450-80f92200-1d1d-11eb-8f7e-71797291a3d6.JPG)

This one is going to be fixed in #52

**Comment by And3rsL** [comment]
maybe it depends about room type?

related to #https://github.com/And3rsL/Deebotozmo/issues/12#issue-733669643

**Comment by ilnonno70** [comment]
Hi @And3rsL reinstalled the integration and now I can see sensors again, but I continue to see ti message in the log. Is that a problem? thx

Logger: deebotozmo.ecovacsiotmq
Source: /usr/local/lib/python3.8/site-packages/deebotozmo/ecovacsiotmq.py:180
First occurred: 0:06:14 (3 occurrences)
Last logged: 9:55:01

1604617573.895115| Error calling API https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=yna5xi&did=4cb2afb0-d96f-49a5-8957-69bbb020597d&td=q&u=dk0gbvuc2643b256&cv=1.67.3&t=a&av=1.3.1 StatusCode 502
1604643980.738563| Error calling API https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=yna5xi&did=4cb2afb0-d96f-49a5-8957-69bbb020597d&td=q&u=dk0gbvuc2643b256&cv=1.67.3&t=a&av=1.3.1 StatusCode 502
1604652900.986403| Error calling API https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=yna5xi&did=4cb2afb0-d96f-49a5-8957-69bbb020597d&td=q&u=dk0gbvuc2643b256&cv=1.67.3&t=a&av=1.3.1 StatusCode 502

**Comment by edenhaus** [comment]
> Hi @And3rsL reinstalled the integration and now I can see sensors again, but I continue to see ti message in the log. Is that a problem? thx
> 
> Logger: deebotozmo.ecovacsiotmq
> Source: /usr/local/lib/python3.8/site-packages/deebotozmo/ecovacsiotmq.py:180
> First occurred: 0:06:14 (3 occurrences)
> Last logged: 9:55:01
> 
> 1604617573.895115| Error calling API https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=yna5xi&did=4cb2afb0-d96f-49a5-8957-69bbb020597d&td=q&u=dk0gbvuc2643b256&cv=1.67.3&t=a&av=1.3.1 StatusCode 502
> 1604643980.738563| Error calling API https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=yna5xi&did=4cb2afb0-d96f-49a5-8957-69bbb020597d&td=q&u=dk0gbvuc2643b256&cv=1.67.3&t=a&av=1.3.1 StatusCode 502
> 1604652900.986403| Error calling API https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=yna5xi&did=4cb2afb0-d96f-49a5-8957-69bbb020597d&td=q&u=dk0gbvuc2643b256&cv=1.67.3&t=a&av=1.3.1 StatusCode 502

Created a new issue for this problem
