### ISSUE TITLE
Getting statuscode 502 from api

### ISSUE THREAD

**Issue by edenhaus** [And3rsL/Deebot-for-hassio#58]
**Describe the bug**
@ilnonno70 and also I, we are getting sometime 502 from the api.
See https://github.com/And3rsL/Deebot-for-hassio/issues/49#issuecomment-722967874

**Configuration.yaml (Remember to delete your credentials)**
```
vacuum:
  - platform: deebot
    username: PRIVATE
    password: PRIVATE
    country: it
    continent: eu
    deviceid: PRIVATE
```

**Screenshots**

**System Informations:**
 - Device: Deebot ozmo 950
 - Home Assistant Version: 0.117.4
 - Hardware: PC with Ubuntu Server 20.04
 - Home Assistant Installation: Docker Core

**Additional context**

**Logs**
```
Logger: deebotozmo.ecovacsiotmq
Source: /usr/local/lib/python3.8/site-packages/deebotozmo/ecovacsiotmq.py:180
First occurred: 0:06:14 (3 occurrences)
Last logged: 9:55:01

1604617573.895115| Error calling API https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=yna5xi&did=4cb2afb0-d96f-49a5-8957-69bbb020597d&td=q&u=dk0gbvuc2643b256&cv=1.67.3&t=a&av=1.3.1 StatusCode 502
1604643980.738563| Error calling API https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=yna5xi&did=4cb2afb0-d96f-49a5-8957-69bbb020597d&td=q&u=dk0gbvuc2643b256&cv=1.67.3&t=a&av=1.3.1 StatusCode 502
1604652900.986403| Error calling API https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=yna5xi&did=4cb2afb0-d96f-49a5-8957-69bbb020597d&td=q&u=dk0gbvuc2643b256&cv=1.67.3&t=a&av=1.3.1 StatusCode 502
```

**Comment by edenhaus** [comment]
@And3rsL I have add traceback to the logger to find out more information.

**Comment by And3rsL** [comment]
Maybe its related to ecovacs portal that sometimes doesnt respond? the official app sometimes return error too

**Comment by edenhaus** [comment]
> Maybe its related to ecovacs portal that sometimes doesnt respond? the official app sometimes return error too

I also thought about it. Will come back if I have more information's

**Comment by edenhaus** [comment]
> Maybe its related to ecovacs portal that sometimes doesnt respond? the official app sometimes return error too

That's probably the reason. We get the 502 from different requests.
@And3rsL Should we do a retry on 502 or silently ignore it (no logger warning) as we will update all status every 10 seconds, if I'm right?

**Comment by 230delphi** [comment]
same error here; in my case seems like i need a HA restart to recover.

**Comment by edenhaus** [comment]
> same error here; in my case seems like i need a HA restart to recover.

This warning can be ignored if the status code is 502 and no restart is needed.
@230delphi  If you need to restart to recover you have probably a other issue, please check your log and open a new issue if needed.
