### ISSUE TITLE
Map detection

### ISSUE THREAD

**Issue by SmartM-ui** [And3rsL/Deebot-for-hassio#59]
Hi Andrea,
having a house on two floors, I often have to use the official app to make the robot locate the map.
Is it possible to integrate this command also in the custom component?

Welcome @edenhaus
Saluti da Roma :-)

**Comment by And3rsL** [comment]
Hi,
Do you mean this command?

![Screenshot_20201107-224706.jpg](https://user-images.githubusercontent.com/31848430/98451967-53f8a500-214b-11eb-8143-c4a87e0cf3ac.jpg)

**Comment by SmartM-ui** [comment]
> Hi,
> Do you mean this command?
> 
> ![Screenshot_20201107-224706.jpg](https://user-images.githubusercontent.com/31848430/98451967-53f8a500-214b-11eb-8143-c4a87e0cf3ac.jpg)

Hi @And3rsL,
exact the command is to be performed through the GPS icon of  the official app. Is it possible to recover the sensor and import it into your custom?

Thanks

**Comment by SmartM-ui** [comment]
Hi @And3rsL ,
do I have hope in the release of 1.9.8 with the required option or should I upgrade to 1.9.7?

I seemed to have read that the transition from version 1.9.4 (my current) to the next version (1.9.5) involved having to review the various sensors / automations / cards.

Does that still apply to the transition from 1.9.4 to 1.9.7?

Thanks

**Comment by And3rsL** [comment]
Introduced with https://github.com/And3rsL/Deebot-for-hassio/tree/1.9.8 release

**Comment by SmartM-ui** [comment]
> Introduced with https://github.com/And3rsL/Deebot-for-hassio/tree/1.9.8 release

THANKS!
