### ISSUE TITLE
Sensor for Battery

### ISSUE THREAD

**Issue by helmut-hoffer-von-ankershoffen** [And3rsL/Deebot-for-hassio#66]
Hi, a sensor for the battery would be great. Cheers

**Comment by edenhaus** [comment]
the battery level is already as attribute available. See my screenshot below.
You can access attributes everywhere, where you can access a entity. If you really want to have e separate entity, you can use [template](https://www.home-assistant.io/integrations/template/) integration of home assistant.

![grafik](https://user-images.githubusercontent.com/26537646/103176754-e0cefd80-4874-11eb-85b3-022566671b91.png)

**Comment by helmut-hoffer-von-ankershoffen** [comment]
I see, thx.
