### ISSUE TITLE
Debot integration out of service

### ISSUE THREAD

**Issue by Niconath** [And3rsL/Deebot-for-hassio#70]
Hello,
My deebot is no longer running on HA as of today.
Here are the logs
`Logger: homeassistant.setup
Source: custom_components/deebot/__init__.py:71
First occurred: 13:53:37 (1 occurrences)
Last logged: 13:53:37

Error during setup of component deebot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deebot/__init__.py", line 55, in setup
    HUB = DeebotHub(config[DOMAIN])
  File "/config/custom_components/deebot/__init__.py", line 71, in __init__
    self.ecovacs_api = EcoVacsAPI(
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 57, in __init__
    self.auth_code = self.__call_main_api('user/getAuthCode',
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 101, in __call_main_api
    raise RuntimeError("failure code {} ({}) for call {} and parameters {}".format(
RuntimeError: failure code 0002 (校验异常) for call user/getAuthCode and parameters (('uid', '20200701214355_1ce4*********'), ('accessToken', '0c92***********'))`

`Logger: deebotozmo
Source: /usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py:100
First occurred: 13:53:36 (1 occurrences)
Last logged: 13:53:36

call to user/getAuthCode failed with {'code': '0002', 'msg': '校验异常', 'time': 1609678416639}`

Thanks to you

**Comment by K-RAD** [comment]
Same here

```
Logger: deebotozmo
Source: /usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py:100
First occurred: 2:40:07 PM (1 occurrences)
Last logged: 2:40:07 PM

call to user/login failed with {'code': '0001', 'msg': '操作失败', 'time': 1609677607905, 'data': None}
```

```
Logger: homeassistant.setup
Source: custom_components/deebot/__init__.py:71
First occurred: 2:40:09 PM (1 occurrences)
Last logged: 2:40:09 PM

Error during setup of component deebot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deebot/__init__.py", line 55, in setup
    HUB = DeebotHub(config[DOMAIN])
  File "/config/custom_components/deebot/__init__.py", line 71, in __init__
    self.ecovacs_api = EcoVacsAPI(
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 52, in __init__
    login_info = self.__call_main_api('user/login',
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 101, in __call_main_api
    raise RuntimeError("failure code {} ({}) for call {} and parameters {}".format(
RuntimeError: failure code 0001 (操作失败) for call user/login and parameters (('account', 'SOBINWnDP5/ipBBXy7mg7REhpxokAZeMT/F6UvtyVys7m9bv1Ivbiji3JKhmh8gEEnQMypvBpwdhqTmvwkA1/nB3B1C3pX/LEafXz5ntI+hapd+ZPGK6+ws6AVjL5EM3Qa87wzytf/qmyHIelGUZHr/vgq2vFLpTU3wXwmyzmeg='), ('password', '1V9HOj4fEn8TwHQfJ+z6bZXZySmwBFZouwAIQ9tzWiNxxT18RdhSlUlWH3/uBoC2AdpwscMe+uovSRjkdDzeXTjHy/Xa0ZFvoLluJv555Mj5C9XPYTpETZq6Qq1TnpMmCuiGJmiz8oD2DMDMDQ1Hu4jeHTn6JjaCTUjVyp7hoWg='))

```

**Comment by Niconath** [comment]
After several restarts the integration seems to be back, maybe a problem for ecovacs.

**Comment by And3rsL** [comment]
Yes, sometimes their servers stop working

**Comment by mrbungle64** [comment]
@And3rsL @Niconath @K-RAD 

It's not caused by Deebotozmo or Deebot-for-hassio.
I am also experiencing the same problem [my Library](https://github.com/mrbungle64/ecovacs-deebot.js).

**Comment by Niconath** [comment]
yes finally the mistake comes back to me too

**Comment by And3rsL** [comment]
> @And3rsL @Niconath @K-RAD 
> 
> It's not caused by Deebotozmo or Deebot-for-hassio.
> I am also experiencing the same problem with [my Library](https://github.com/mrbungle64/ecovacs-deebot.js).
> 
> But I don't think that the servers stop working. There are problems with authentication.
> 
> 操作失败 = Operation fehlgeschlagen
> 
> and I get also:
> 用户登录过期 = User login expired

It happened some months ago too, maybe some expired token every 6 months ?

**Comment by mrbungle64** [comment]
> > @And3rsL @Niconath @K-RAD
> > It's not caused by Deebotozmo or Deebot-for-hassio.
> > I am also experiencing the same problem with [my Library](https://github.com/mrbungle64/ecovacs-deebot.js).
> > But I don't think that the servers stop working. There are problems with authentication.
> > 操作失败 = Operation fehlgeschlagen
> > and I get also:
> > 用户登录过期 = User login expired
> 
> It happened some months ago too, maybe some expired token every 6 months ?

@And3rsL 
I don't think so, because in my experience, these error messages occurred repeatedly that day, but still more or less randomly.
