### ISSUE TITLE
Deebot NOT generate the Map

### ISSUE THREAD

**Issue by manny199** [And3rsL/Deebot-for-Hassio#71]
Hello, great works but I have problems with map that not shows on my lovelace card.

Below is my configuration:
```
deebot:
  username: xxxxx@gmail.it
  password: xxxxxxx
  country: IT
  continent: EU
  deviceid:
    - ADDDBCDXXXXXXXXXXXXX
  live_map: True
  show_color_rooms: True
  livemappath: 'www/'

camera:
  - platform: generic
    name: "Ultima pulizia"
    still_image_url: "https://xxxxxxx.duckdns.org:1111/local/live_map.png"

```
The error in the log is:
```
Logger: homeassistant.helpers.entity
Source: custom_components/deebot/vacuum.py:209
First occurred: 12:02:39 (1 occurrences)
Last logged: 12:02:39
Update for vacuum.ambrogio fails

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/home/homeassistant/.homeassistant/custom_components/deebot/vacuum.py", line 209, in async_update
    with open(self._live_map_path, "wb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'www/ambrogio_liveMap.png'
```
If I check [sensor.ambrogio_last_clean_image], I see the image and link is ok but then not generate image on www folder

**Comment by And3rsL** [comment]
What platform do u use? Windows/Linux or hassio

**Comment by manny199** [comment]
Home Assistant Core on Raspbian

**Comment by And3rsL** [comment]
last_clean_image and liveMap are 2 different things

can you try to manually create a file called "ambrogio_liveMap.png" in the www folder?

**Comment by Yterz** [comment]
I had a similar issue, now solved. Not sure what part exactly solved it, but here's the modification I did : 
```
[...]
  live_map: True
  show_color_rooms: False # with true it was still not showing color + was blocking image refreshing
  livemappath: 'www/'

camera:
  - platform: generic
    name: Deebot_live_map
    still_image_url: "https://192.168.1.50:8123/local/DeebYterz_liveMap.png" #I stayed local
    verify_ssl: false #to prevent any issue as I'm in https
```

Also, I struggled to understand the "www/" path. I ended up understanding that I need to have a folder /config/www/ for hassio. So with the add-ons _Samba share_ I manually created the "/config/www" folder, as it didn't existed yet on my config.

And with that configuration + the "/config/www" folder created I started to get the map.

Later I found that HACS was using that /config/www/ folder for Frontend content when I downloaded Vacuum Card, so I guess it would have been created with that as well

**Comment by bolderbast** [comment]
Hi! I love this addon, very happy to be able to control and view the status of my Vacuum!
However, it looks like I am having the same issue. Any help would be very mucht appreciated.

Environment:
- Ecovacs Deebot Ozmo 950 vacuum robot
- Country: Netherlands
- Home Assistant Core 2021.1.5 running on Arch Linux
- Deebot for Hassio 2.0.1 installed through HACS
- All works (sensors and commands), except for the live map
- /var/lib/private/hass/www exists and has permissions set for the "hass" user. Also, there are other images there which load fine in the frontend.
- Tried creating the missing file using the "touch" command and setting permissions. Issue persists even after Home Assistant restart

Configuration.yaml:
`deebot:
  username: !secret deebot-username
  password: !secret deebot-password
  country: nl
  continent: eu
  deviceid: !secret deebot-deviceid
  live_map: True
  show_color_rooms: False
  livemappath: 'www/'`

Error:
`Mar 04 09:49:51 hortensia hass[991048]: 2021-03-04 09:49:51 ERROR (MainThread) [homeassistant.helpers.entity] Update for vacuum.mevrouw_baktaart fails
Mar 04 09:49:51 hortensia hass[991048]: Traceback (most recent call last):
Mar 04 09:49:51 hortensia hass[991048]:   File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
Mar 04 09:49:51 hortensia hass[991048]:     await self.async_device_update()
Mar 04 09:49:51 hortensia hass[991048]:   File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 474, in async_device_update
Mar 04 09:49:51 hortensia hass[991048]:     raise exc
Mar 04 09:49:51 hortensia hass[991048]:   File "/var/lib/hass/custom_components/deebot/vacuum.py", line 215, in async_update
Mar 04 09:49:51 hortensia hass[991048]:     with open(self._live_map_path, "wb") as fh:
Mar 04 09:49:51 hortensia hass[991048]: FileNotFoundError: [Errno 2] No such file or directory: 'www/Mevrouw Baktaart_liveMap.png'`

Please let me know if there is any more information needed to investigate!

**Comment by And3rsL** [comment]
Please try to remove spaces in your robot name

**Comment by bolderbast** [comment]
Thanks for the quick response!
I renamed the robot and restarted Home Assistant. Unfortunately I still have the sam error:

```
Mar 04 15:47:13 hortensia hass[1029206]: 2021-03-04 15:47:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for vacuum.mevrouw_baktaart fails
Mar 04 15:47:13 hortensia hass[1029206]: Traceback (most recent call last):
Mar 04 15:47:13 hortensia hass[1029206]:   File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
Mar 04 15:47:13 hortensia hass[1029206]:     await self.async_device_update()
Mar 04 15:47:13 hortensia hass[1029206]:   File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 474, in async_device_update
Mar 04 15:47:13 hortensia hass[1029206]:     raise exc
Mar 04 15:47:13 hortensia hass[1029206]:   File "/var/lib/hass/custom_components/deebot/vacuum.py", line 215, in async_update
Mar 04 15:47:13 hortensia hass[1029206]:     with open(self._live_map_path, "wb") as fh:
Mar 04 15:47:13 hortensia hass[1029206]: FileNotFoundError: [Errno 2] No such file or directory: 'www/MevrouwBaktaart_liveMap.png'
```

Please let me know it there is anything else I can try!

**Comment by And3rsL** [comment]
try with livemappath: '/'

**Comment by bolderbast** [comment]
Hi,

tried:

`livemappath: '/'`

and restarted HA. Unfortunately, it still fails, however, with a different error:

```
Mar 04 16:52:57 hortensia hass[1036575]: 2021-03-04 16:52:57 ERROR (MainThread) [homeassistant.helpers.entity] Update for vacuum.mevrouw_baktaart fails
Mar 04 16:52:57 hortensia hass[1036575]: Traceback (most recent call last):
Mar 04 16:52:57 hortensia hass[1036575]:   File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
Mar 04 16:52:57 hortensia hass[1036575]:     await self.async_device_update()
Mar 04 16:52:57 hortensia hass[1036575]:   File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 474, in async_device_update
Mar 04 16:52:57 hortensia hass[1036575]:     raise exc
Mar 04 16:52:57 hortensia hass[1036575]:   File "/var/lib/hass/custom_components/deebot/vacuum.py", line 215, in async_update
Mar 04 16:52:57 hortensia hass[1036575]:     with open(self._live_map_path, "wb") as fh:
Mar 04 16:52:57 hortensia hass[1036575]: OSError: [Errno 30] Read-only file system: '/MevrouwBaktaart_liveMap.png'
```

Decided to try with the full path:

`livemappath: '/var/lib/pribate/hass/www/'`

Gives me back the original error:

```
Mar 04 17:00:12 hortensia hass[1037521]: 2021-03-04 17:00:12 ERROR (MainThread) [homeassistant.helpers.entity] Update for vacuum.mevrouw_baktaart fails
Mar 04 17:00:12 hortensia hass[1037521]: Traceback (most recent call last):
Mar 04 17:00:12 hortensia hass[1037521]:   File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
Mar 04 17:00:12 hortensia hass[1037521]:     await self.async_device_update()
Mar 04 17:00:12 hortensia hass[1037521]:   File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 474, in async_device_update
Mar 04 17:00:12 hortensia hass[1037521]:     raise exc
Mar 04 17:00:12 hortensia hass[1037521]:   File "/var/lib/hass/custom_components/deebot/vacuum.py", line 215, in async_update
Mar 04 17:00:12 hortensia hass[1037521]:     with open(self._live_map_path, "wb") as fh:
Mar 04 17:00:12 hortensia hass[1037521]: FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/pribate/hass/www/MevrouwBaktaart_liveMap.png'
```

Decided to try commenting the livemappath setting out:

`#  livemappath: '/var/lib/pribate/hass/www/'`

Still the same error:

```
Mar 04 17:05:34 hortensia hass[1038308]: 2021-03-04 17:05:34 ERROR (MainThread) [homeassistant.helpers.entity] Update for vacuum.mevrouw_baktaart fails
Mar 04 17:05:34 hortensia hass[1038308]: Traceback (most recent call last):
Mar 04 17:05:34 hortensia hass[1038308]:   File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
Mar 04 17:05:34 hortensia hass[1038308]:     await self.async_device_update()
Mar 04 17:05:34 hortensia hass[1038308]:   File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 474, in async_device_update
Mar 04 17:05:34 hortensia hass[1038308]:     raise exc
Mar 04 17:05:34 hortensia hass[1038308]:   File "/var/lib/hass/custom_components/deebot/vacuum.py", line 215, in async_update
Mar 04 17:05:34 hortensia hass[1038308]:     with open(self._live_map_path, "wb") as fh:
Mar 04 17:05:34 hortensia hass[1038308]: FileNotFoundError: [Errno 2] No such file or directory: 'www/MevrouwBaktaart_liveMap.png'
Mar 04 17:05:37 hortensia hass[1038308]: 2021-03-04 17:05:37 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.playstation_tuinhuisje is taking over 10 seconds
```

Permissions of the "www" driectory where the file is supposed to go:

```
# ls -lAh '/var/lib/private/hass/'
...
drwxr-xr-x  2 hass hass  311 Mar  4 15:44 www
```

Permissions of the file I manually created:

```
# ls -lAh '/var/lib/private/hass/www/'
...
-rw-r--r-- 1 hass hass    0 Mar  4 09:44 MevrouwBaktaart_liveMap.png
```
