### ISSUE TITLE
Sensor for fan speed missing?

### ISSUE THREAD

**Issue by Jonasn97** [And3rsL/Deebot-for-hassio#73]
Hey, 
I am just working on my homeassistant dashboard and found some nice layout for the vacuum:
https://community.home-assistant.io/t/fixed-ecovacs-deebot-2019-ozmo-series-working-library/126319/307
As I was adapting the code to my setup, I couldn't see the sensors for the fan.
So my question is: Are they missing or should I try to implement them myself?
Thanks :)

**Comment by And3rsL** [comment]
Hi, you can get fan speed by vacuum attributes

**Comment by Jonasn97** [comment]
> Hi, you can get fan speed by vacuum attributes

Thanks :) I still don’t know how to adapt the code yet, but I‘ll look into it :)
Got some idea already.
