### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by jfbarens** [And3rsL/Deebot-for-hassio#75]
First time user of this (or any other) custom component. I installed the component through HACS, no problem there (folder is created in custom_components. After restarting and adding the configuration to configuration.yaml I get the error that the package is unable to install.

My Configuration.yaml

deebot:
  username: USER
  password: PASS
  country: nl
  continent: eu
  deviceid:
    - ABCDE

System Information:

Device: Deebot Ozmo T8+
Home Assistant Version: 2021.1.4 (latest)
Hardware: VPS
Home Assistant Installation: Docker on Debian 10 without Supervisor
HACS version: 1.10.0 (latest)
Repository: 1.9.8 (latest)

Logs
2021-01-22 14:55:24 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package deebotozmo==1.7.4:
2021-01-22 14:55:24 ERROR (MainThread) [homeassistant.components.homeassistant] Component error: deebot - Requirements for deebot not found: ['deebotozmo==1.7.4'].

**Comment by And3rsL** [comment]
I dont know how packages work on docker for home assistant
but can you try to install
https://pypi.org/project/deebotozmo/ ?

`pip install deebotozmo`

**Comment by jfbarens** [comment]
Didn't know that I needed to install that. That worked, thanks!
