### ISSUE TITLE
Add support for Ozmo 930

### ISSUE THREAD

**Issue by momab** [And3rsL/Deebot-for-hassio#85]
HI there,

I know this is not an Issue, but is there any chance the OZMO 930 will be added in the future?
I really appreciate your work you put into this Component, so if you need any help, I am here to help you.

Greets,
momab

**Comment by niklasmoeller** [comment]
I would appreciate that too and be willing to support wherever I can.

**Comment by edenhaus** [comment]
According to https://github.com/bmartin5692/bumper/blob/master/README.md#compatibility the 903 used XMPP for communication and this custom component supports only MQTT.
Please try to use the https://www.home-assistant.io/integrations/ecovacs/
