### ISSUE TITLE
Vacuum Status not returned

### ISSUE THREAD

**Issue by StefanoGiu** [And3rsL/Deebot-for-hassio#9]
I've modified vacuum.py with this:

        data['vacuum_status'] = self.device.vacuum_status

It would be great also to have a way to decode the value in Italian or any other language.

If possible, pls support it.

**Comment by And3rsL** [comment]
Vacuum report its status by its state

https://github.com/And3rsL/Deebot-for-hassio/blob/5555ad68f3815864049a168b540ad0757df013bf/custom_components/deebot/vacuum.py#L156

Cant support other language for now
