### ISSUE TITLE
OZMO 905

### ISSUE THREAD

**Issue by danielsmith89** [And3rsL/Deebot-for-Hassio#90]
Hi, does this custom component support the 905, can't see anything about it in the documentation. Thanks

**Comment by danielsmith89** [comment]
Tried it, doesn't appear to work for the 905. The reason I ask is I think it uses similar firmware to the 920, which you say does work. Obviously, the firmware is more different than I thought.

**Comment by edenhaus** [comment]
Check out my comment: https://github.com/And3rsL/Deebot-for-hassio/issues/85#issuecomment-793901333
Maybe you can use the official integration

**Comment by edenhaus** [comment]
If you have the possibility to verify which URLs your bot is connecting and also verify that he is connecting to the MQTT ones.
See https://bumper.readthedocs.io/en/latest/DNS_Setup/

Also start logging in debug and check your logs. Maybe you will find out more.
We only have the Deebot Ozmo 950 and not your model

**Comment by danielsmith89** [comment]
Looks like it's finding it, but it just sits there as unavailable

`2021-03-09 14:08:14 DEBUG (SyncWorker_7) [deebotozmo] got {'todo': 'result', 'result': 'ok', 'devices': [{'did': '5d18df3f-ddd1-4bc0-ba8d-cd63adfb4b77', 'name': 'E0001344110058850015', 'class': '2pv572', 'resource': 'VEqN', 'nick': 'Downstairs Deebot', 'company': 'eco-ng', 'bindTs': 1602585027924, 'service': {'jmq': 'jmq-ngiot-na.dc.ww.ecouser.net', 'mqs': 'api-ngiot.dc-na.ww.ecouser.net'}}]}
2021-03-09 14:08:14 DEBUG (SyncWorker_7) [deebotozmo] Found robot version OTHER -> 2pv572`

**Comment by danielsmith89** [comment]
Interestingly I'm also seeing some requests from the bot for msg-ww.ecouser.net which would imply it could also be using XMPP

**Comment by mrbungle64** [comment]
@danielsmith89 @edenhaus 

There are 3 communication variants used by Ecovacs for the Deebot vacuum cleaners:
- XMPP (e.g. Slim 2, N79, OZMO 930)
- MQTT/XML (e.g. Deebot 900, OZMO 900)
- MQTT/JSON (e.g. OZMO 920/950, T8 series)

As far as I know the OZMO 905 is simular (or maybe equal) to the OZMO 900.

**Comment by edenhaus** [comment]
#35
