### ISSUE TITLE
What are the differences between this integration and the "official" one inside HA

### ISSUE THREAD

**Issue by cibernox** [And3rsL/Deebot-for-Hassio#98]
Sorry for reporting this as a bug when it's actually a question.

I noticed that HA already has an "official" (https://www.home-assistant.io/integrations/ecovacs/) has on the surface looks similar.
Is this integration related or a beta version of the one included in HA or just a different alternative?

I imagine I might not be the only person wondering this, so maybe a clarification in the readme would be useful.

**Comment by And3rsL** [comment]
HA official component can't connect with new ecovacs robot, it uses the old XML protocol via "SUCKS" Library

**Comment by cibernox** [comment]
Thanks. Maybe a note in the readme about this could come handy. If I was confused maybe other are too.

If this integration is more feature-rich and supports more vacuum models, maybe you should consider speaking with the HA maintainers and have it replace the old one. For what I can see, the SUCKS library is not maintained anymore.

**Comment by cibernox** [comment]
I'm closing this, thanks for answering!
